
env:
  - ARCH=amd64
  - ARCH=arm32v7

sudo: required

language: bash

services:
  - docker

before_script:
  - docker run --rm --privileged multiarch/qemu-user-static:register

script:
  - docker build -t $TRAVIS_REPO_SLUG:$ARCH -f Dockerfile.$ARCH .
